const images = {
  like: require('../assets/like.png'),
  next: require('../assets/next.png'),
  undo: require('../assets/undo.png'),
  match: require('../assets/match.png'),
  menu: require('../assets/menu.png'),
  bell: require('../assets/LoveAttraction/bell.png'),
  bell_ring: require('../assets/LoveAttraction/bell-ring.png'),
  messages: require('../assets/LoveAttraction/message.png'),
  logo: require('../assets/LoveAttraction/header-angie2.png'),
  userPic: require('../assets/LoveAttraction/profile/man.png'),
  userPic1: require('../assets/LoveAttraction/photo-racim.png'),
  userPic2: require('../assets/pexels-leah-kelley.jpg'),
  userPic3: require('../assets/LoveAttraction/photo-stock-male.jpg'),
  userPic4: require('../assets/LoveAttraction/photo-stock-female.jpg'),
  ellipse: require('../assets/LoveAttraction/Ellipse.png'),
  ellipseWhite: require('../assets/LoveAttraction/EllipseWhite.png'),
  ellipseGrey: require('../assets/LoveAttraction/EllipseGrey.png'),
  pencil: require('../assets/LoveAttraction/pencil.png'),
  menuIcon: require('../assets/LoveAttraction/TabBar/menu.png'),
  menuIconActif: require('../assets/LoveAttraction/TabBar/menu-actif.png'),
  profilHomme: require('../assets/LoveAttraction/TabBar/profil-homme.png'),
  profilHommeActif: require('../assets/LoveAttraction/TabBar/profil-homme-actif.png'),
  profilFemme: require('../assets/LoveAttraction/TabBar/profil-femme.png'),
  profilFemmeActif: require('../assets/LoveAttraction/TabBar/profil-femme-actif.png'),
  notifications: require('../assets/LoveAttraction/TabBar/notifications.png'),
  notificationsActif: require('../assets/LoveAttraction/TabBar/notifications-actif.png'),
  recherche: require('../assets/LoveAttraction/TabBar/recherche.png'),
  rechercheActif: require('../assets/LoveAttraction/TabBar/recherche-actif.png'),
  message: require('../assets/LoveAttraction/TabBar/message.png'),
  messageActif: require('../assets/LoveAttraction/TabBar/message-actif.png'),
  profile: {
    castle: require('../assets/LoveAttraction/profile/Castle.png'),
    castleActif: require('../assets/LoveAttraction/profile/Castle-actif.png'),
    coeur: require('../assets/LoveAttraction/profile/health.png'),
    coeurActif: require('../assets/LoveAttraction/profile/health-actif.png'),
    man: require('../assets/LoveAttraction/profile/man.png'),
    manActif: require('../assets/LoveAttraction/profile/man-actif.png'),
    woman: require('../assets/LoveAttraction/profile/woman.png'),
    womanActif: require('../assets/LoveAttraction/profile/woman-actif.png'),
    planete: require('../assets/LoveAttraction/profile/planet.png'),
    planeteActif: require('../assets/LoveAttraction/profile/planet-actif.png'),
    sexe: require('../assets/LoveAttraction/profile/sexe.png'),
    sexeActif: require('../assets/LoveAttraction/profile/sexe-actif.png'),
  },
};

export default images;
